name: Bug Report
description: Report a bug or unexpected behavior in YOLOEZ
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug.
        Please fill out this form as completely as possible.

  - type: input
    id: version
    attributes:
      label: YOLOEZ Version / Commit
      description: Release version or commit hash
      placeholder: e.g. v0.1.0 or a1b2c3d
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - Linux
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: e.g. 3.12.0
    validations:
      required: true

  - type: dropdown
    id: hardware
    attributes:
      label: Hardware Used
      options:
        - CPU only
        - GPU (CUDA)
    validations:
      required: true

  - type: input
    id: gpu
    attributes:
      label: GPU Model (if applicable)
      placeholder: e.g. RTX 3090
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide a clear, minimal set of steps
      placeholder: |
        1. Open YOLOEZ
        2. Load dataset
        3. Start training
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Messages
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Screen Recordings (GUI issues)
    validations:
      required: false